### ISSUE TITLE
vers 520-61-05

### ISSUE THREAD

**Issue by republicus** [flathub/org.freedesktop.Platform.GL.nvidia#130]
Nvidia repo updated host to driver version 520-61-05. 
Flatpak updated to 515-65-01

I just found this github page when trying to search my problem. The instructions are minimal and I'm not sure if i should be cloning the repo to edit versions.sh or editing whats provided in flatpak. ;\

**Comment by aloisklink** [comment]
I'm having the same issue, I'm on driver version v520.61.05 (the latest NVIDIA compute driver).

Unfortunately NVIDIA hasn't yet put their driver version v520.61.05 on https://www.nvidia.com/en-us/drivers/unix/ yet.

I'm guessing this is because the v520.61.05 is expected to be for compute only, since it adds support for the H100.

However, v520.56.06 is the latest display driver (despite having a lower version number), and it adds support for the 4090 but not the H100.

My recommendation is to temporarily revert your NVIDIA drivers until NVIDIA releases a new driver, which will hopefully appear both at https://www.nvidia.com/en-us/drivers/unix/ and the NVIDIA compute repos.

**Comment by cathaysia** [comment]
ref: https://github.com/guibou/nixGL/issues/119

**Comment by cathaysia** [comment]
some nvidia were taken elsewhere.
For example: v520.61.05 in http://us.download.nvidia.com/tesla/520.61.05/NVIDIA-Linux-x86_64-520.61.05.run

**Comment by cathaysia** [comment]
this should close by https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/134
